# Generated by Django 4.0.5 on 2022-07-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVapp', '0002_siteusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteusers',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
